yum install -y \
    make \
    rpm-build \
    yum-utils \
    apr-devel \
    cyrus-sasl-devel \
    gcc \
    gcc-c++ \
    git \
    java-1.8.0-openjdk-devel \
    krb5-devel \
    libcurl-devel \
    patch \
    python \
    python-devel \
    subversion-devel \
    tar \
    unzip \
    wget \
    zlib-devel \
    bluez-libs-devel \
    bzip2-devel \
    expat-devel \
    gdbm-devel \
    gmp-devel \
    libdb-devel \
    ligGl-devel \
    libX11-devel \
    ncurses-devel \
    openssl-devel \
    readline-devel \
    sqlite-devel \
    systemtap-sdt-devel \
    tcl-devel \
    tix-devel \
    tk-devel \
    valgrint-devel \
    python-setuptools \
    python-pip \
    expat-devel \
    libdb-devel \
    libffi-devel \
    libGL-devel \
    valgrind-devel \
    python-pip
